```{r,echo=FALSE,message=FALSE}
source("setup.R")
```

# Plugins {#plugins}

## tad {#plugin-tad}

__Purpose__
Advanced calculation time after dose within your model. We call this "advanced"
because it lets you track doses in multiple compartments. See the note below 
about a simpler way to calculate time after dose that should work fine if doses
are only in a single compartment. This functionality is provided by mrgsolve. 

__Usage__

First, tell `mrgsolve` that you want to use the `tad` plugin

```{c, eval = FALSE}
$PLUGIN tad
```

The create `tadose` objects, one for each compartment where you want to track
time after dose. One approach is to do this in `[ global ]`

```{c, eval = FALSE}
[plugin] tad

[ global ] 
mrg::tadose tad_cmt_1(1); 
mrg::tadose tad_cmt_2(2);
```

Notice that we pass the compartment number that we want to track in each 
case and also that we refer to the `mrg::` namespace for the `tadose` class. 

The `tadose` objects contain the following (public) members

- `cmt` the compartment to track
- `told` the time of last dose; defaults to `-1e9`
- `had_dose` indicates if a dose has already been given for the current 
  individual
- `tad(self)` the function to call to calculate time after dose
  - the `self` object (Section \@ref(self-object)) must be passed as the only
    argument
  - when the member function is called prior to the first administered dose, a 
    value of `-1.0` is returned
- `reset()` resets the state of the object; be sure to reset prior to simulating
  a new individual

As an example, you can call the `reset()` method on one of the `tadose` objects

```{c, eval = FALSE}
tad_cmt_1.reset();
```


You can find the source code for this object 
[here](https://github.com/metrumresearchgroup/mrgsolve/blob/master/inst/base/mrgsolve-tad.h).

A working example model that tracks doses in compartments `1` and `2` is
provided here

```{c, eval = FALSE}
[plugin] tad

[ global ] 
mrg::tadose tad_cmt_1(1); 
mrg::tadose tad_cmt_2(2);

[ pkmodel ] cmt = "GUT,CENT", depot = TRUE

[ param ] CL = 1, V = 20, KA = 1

[ main ] 
capture tad1 = tad_cmt_1.tad(self); 
capture tad2 = tad_cmt_2.tad(self);
```

__Static approach__

Another approach would be to make these static in `[ main ]` but this approach
would only work if you only use these in `[ main ]`; the `[ global ]` approach 
is preferable since then you can access the object in any block (function). 


### Note
Note there is a simpler way to calculate time after dose when only dosing into
a single compartment

```{c, eval = FALSE}
[ main ]
double tad = self.tad();
```

The `self` object (Section \@ref(self-tad)) contains a `tad()` member which 
will track time after dose. Note that this needs to be called every record. 


## CXX11  {#plugin-cxx11}

__Purpose__

Compile your model file with `C++11` standard.

__Usage__ 

```{c, eval = FALSE}
$PLUGIN CXX11
```

## Rcpp

__Purpose__

Link to `Rcpp` headers into your model.

__Usage__ 

```{c, eval = FALSE}
$PLUGIN Rcpp
```

Note that once your model is linked to `Rcpp`, you can start using that 
functionality immediately (without including `Rcpp.h`).

Information about `Rcpp` can be found here: https://github.com/RcppCore/Rcpp

## Rcpp

__Purpose__

Link to `RcppArmadillo` headers into your model. 

__Usage__ 

```{c, eval = FALSE}
$PLUGIN RcppArmadillo
```

Information about `armadillo` can be found here: http://arma.sourceforge.net/
Information about `RcppArmadillo` can be found here: 
https://github.com/RcppCore/RcppArmadillo

## BH

__Purpose__

Link to `boost` headers into your model. 

__Usage__ 

```{c, eval = FALSE}
$PLUGIN BH
```

Note that once your model is linked to `BH` (`boost`), you will be able to 
include the `boost` header file that you need. You have to include the header
file that contains the `boost` function you want to use.

Information about `boost` can be found here: https://boost.org. Information 
about `BH` can be found here: https://github.com/eddelbuettel/bh
